In [9]:
import numpy as np
import pandas as pd
from sergio import sergio

import sys
locate_python = sys.exec_prefix
print(locate_python)

C:\Users\moha456\Anaconda3\envs\my_env


In [10]:
print("My numpy version is: ", np.__version__)

My numpy version is:  1.23.1


# Run SERGIO with CRISPRa gene perturbations

In [11]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRa.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[ 9.75382198, 11.75973383,  8.94737041, ...,  3.89390402,
        10.65061723,  7.4047379 ],
       [ 2.56473823,  2.04671179,  2.34279775, ...,  2.36978405,
         4.17948816,  3.76350467],
       [ 0.56392336,  3.57097325,  0.75411455, ...,  0.28559197,
         4.49877286,  3.01216592],
       [ 5.31896628,  3.65675608,  5.25510103, ...,  5.00895634,
         5.04468764,  2.4391272 ]])

In [12]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0          1         2         3          4          5          6     \
0   14.645920   6.129854  3.923681  2.787130  12.218487   5.969242   3.739527   
1    9.753822  11.759734  8.947370  7.730420  15.013567   8.839603   8.195633   
2    2.564738   2.046712  2.342798  2.471064   3.446806   2.279278   6.504719   
3    0.563923   3.570973  0.754115  1.395651   1.507803   3.681175   0.331354   
4    5.318966   3.656756  5.255101  6.639909   2.743639   2.496965   9.042694   
..        ...        ...       ...       ...        ...        ...        ...   
95   3.276980   0.368469  1.136189  2.000718   2.588525   3.579517   3.767949   
96   2.010332   2.907744  6.468705  7.639861   1.932694   5.711111   1.220501   
97   2.585236   1.646868  8.156967  6.156767   3.895245   3.860240   3.776525   
98  19.876665  15.541774  9.182942  9.811358  22.193177  14.922755  11.364712   
99   1.277235   4.854064  6.983677  6.216845   3.485941   6.504511   2.663160   

         7          8          9     ...      2690       2691       2692  \
0   11.208010   3.634029   8.464664  ...  4.785868   5.468148   4.111418   
1   10.079482   3.343323   9.813044  ...  5.294080   2.512169   3.835548   
2    3.032254   1.589948   1.537630  ...  6.197884   4.344770   1.888846   
3    2.127963   1.407007   2.714310  ...  0.980435   3.140487   1.164305   
4    1.511402   2.534787   3.255239  ...  4.388519   1.464051   0.482029   
..        ...        ...        ...  ...       ...        ...        ...   
95   2.024018   1.544885   1.581309  ...  5.859190   5.611547   5.609552   
96   2.459507   6.234918   3.303485  ...  0.717235   1.014816   1.820354   
97   4.829293   3.130698   4.192340  ...  6.125175   1.907511   3.024394   
98  21.440351  13.776460  16.866318  ...  8.117566  14.101780  12.860024   
99   4.889996   8.420529  11.108350  ...  5.239183   2.451596   4.213822   

        2693       2694       2695      2696      2697       2698      2699  
0   7.220545   6.025953   5.783589  6.079701  6.600249   5.191180  6.225857  
1   4.468367   2.401603   4.643612  5.494734  3.893904  10.650617  7.404738  
2   2.807837   0.000000   3.112705  1.637384  2.369784   4.179488  3.763505  
3   2.488040   1.357203   0.420078  4.631035  0.285592   4.498773  3.012166  
4   3.906789   0.331736   0.134412  2.786325  5.008956   5.044688  2.439127  
..       ...        ...        ...       ...       ...        ...       ...  
95  4.832750   4.916567   1.765798  2.129445  2.914145   4.169545  3.401218  
96  2.156384   0.850549   0.850200  4.050571  1.830222   0.177988  4.610262  
97  3.788833   6.812847   3.265099  6.666092  1.859033   3.745166  2.849744  
98  6.654513  13.427385  10.082579  7.041176  8.643038  11.346795  7.087685  
99  3.616569   7.549119   2.118929  6.073048  3.950837   4.745253  1.847589  

[100 rows x 2700 columns]

In [13]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRa_perturb.csv') 

# Add technical noise

In [14]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
#expr_O[1:5]

In [15]:
expr_O = np.concatenate(expr_O, axis = 1)
expr_O[1:5]

array([[ 9.75382198, 11.75973383,  8.94737041, ...,  3.89390402,
        10.65061723,  7.4047379 ],
       [ 2.56473823,  2.04671179,  2.34279775, ...,  2.36978405,
         4.17948816,  3.76350467],
       [ 0.56392336,  3.57097325,  0.75411455, ...,  0.28559197,
         4.49877286,  3.01216592],
       [ 7.92188203,  5.44624439,  7.82676335, ...,  7.46016408,
         7.51338103,  3.6327506 ]])

In [16]:
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O.csv') 

In [28]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 0, ..., 0, 1, 0],
       [2, 2, 0, ..., 1, 0, 0],
       [0, 2, 0, ..., 2, 0, 0],
       [6, 0, 0, ..., 2, 0, 1]])

In [29]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L.csv') 

In [30]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [31]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L_D.csv') 

# Run SERGIO with CRISPRi gene perturbations

In [32]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRi.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[ 7.72525409,  2.95843753, 11.60972175, ...,  4.5899805 ,
         2.01403288,  1.18321203],
       [ 3.45916029,  0.92443329,  1.42740769, ...,  0.92721584,
         0.92730415,  5.46993506],
       [ 0.08323557,  4.82283682,  3.96661644, ...,  0.36201732,
         2.24907249,  0.22419786],
       [ 7.02495789,  1.5365929 ,  0.89239988, ...,  0.1963121 ,
         1.18370644,  1.46587655]])

In [33]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0         1          2          3          4          5     \
0    6.263376  4.036806   6.547681   6.240117  13.946657   4.328626   
1    7.725254  2.958438  11.609722   9.150930   9.541440   5.381068   
2    3.459160  0.924433   1.427408   5.913417   0.249530   3.753577   
3    0.083236  4.822837   3.966616   0.368072   1.390202   2.568694   
4    7.024958  1.536593   0.892400   0.522832   3.546274   3.606492   
..        ...       ...        ...        ...        ...        ...   
95   2.696050  1.942870   0.201537   1.617369   0.836901   1.004719   
96   2.396467  2.998353   3.564014   5.952643   3.565933   3.613404   
97   5.043487  4.599972   7.726891   3.008907   4.452663   4.015303   
98  17.984010  9.287442   8.937976  14.443882  13.713259  13.663183   
99   4.801750  1.204089   6.875782   6.943284   6.967604   5.214487   

         6         7          8          9     ...       2690       2691  \
0    5.703986  4.966865   4.977107   6.688251  ...   1.855933   3.354489   
1    7.307132  2.909911   5.456767   8.524224  ...   7.381059   7.961509   
2    0.356265  3.047600   0.882627   1.931019  ...   0.000000   2.589619   
3    2.221143  2.087504   5.710673   1.557501  ...   0.268035   2.812606   
4    2.441651  2.663397   1.328837   0.577941  ...   1.118333   2.254918   
..        ...       ...        ...        ...  ...        ...        ...   
95   0.703915  0.525028   1.877005   5.532195  ...   3.467088   3.111192   
96   2.676141  1.952411   2.924348   1.956841  ...   5.156742   1.547597   
97   4.725798  3.961461   6.239811   5.875211  ...   5.760624   6.623473   
98  12.244201  9.442358  10.226879  13.595753  ...  13.367435  18.070606   
99   7.894290  7.314397   1.705206   6.088512  ...   4.437160   7.615450   

        2692       2693      2694       2695       2696      2697      2698  \
0   1.216914   4.276381  2.786392   3.186129   5.219347  3.956841  4.203140   
1   4.131200   4.681077  2.617458   6.404109  11.518527  4.589980  2.014033   
2   1.140223   2.936474  1.516707   5.235417   3.643153  0.927216  0.927304   
3   1.649703   2.086139  2.018234   0.312805   2.280586  0.362017  2.249072   
4   1.074100   1.239761  0.035521   0.566854   5.997339  0.196312  1.183706   
..       ...        ...       ...        ...        ...       ...       ...   
95  5.890047   3.068264  0.040681   3.249357   6.002888  1.649415  9.871249   
96  1.434975   0.957908  2.562400   2.371849   3.174202  3.139563  2.310021   
97  4.693607  12.589169  6.585128   0.947010  10.526223  4.504532  4.998541   
98  8.051400  14.490016  7.402030  12.718447  13.376472  7.501637  7.525170   
99  1.823384   7.312475  5.680335   6.503213   4.130301  1.289966  1.497083   

         2699  
0    4.947541  
1    1.183212  
2    5.469935  
3    0.224198  
4    1.465877  
..        ...  
95   4.083038  
96   0.000000  
97   4.609403  
98  10.103761  
99   7.650564  

[100 rows x 2700 columns]

In [34]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRi_perturb.csv') 

# Add technical noise

In [35]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]


array([[ 6,  2, 13, ...,  5,  1,  3],
       [ 2,  4,  0, ...,  0,  0,  6],
       [ 0,  5,  3, ...,  0,  1,  0],
       [12,  2,  0, ...,  0,  0,  1]])

In [36]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O.csv') 

In [38]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 4, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 2],
       [0, 1, 1, ..., 0, 2, 0],
       [2, 1, 2, ..., 0, 0, 1]])

In [39]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L.csv') 

In [40]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 4, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L_D.csv') 