In [10]:
import numpy as np
import pandas as pd
from sergio import sergio

import sys
locate_python = sys.exec_prefix
print(locate_python)

C:\Users\moha456\Anaconda3\envs\my_env


In [11]:
print("My numpy version is: ", np.__version__)

My numpy version is:  1.23.1


# Run SERGIO with CRISPRa gene perturbations

In [12]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRa.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[6.23752925, 7.1113237 , 3.89749497, ..., 2.74443197, 0.7324199 ,
        7.37471824],
       [5.2209274 , 3.51924266, 0.81443726, ..., 0.54951356, 0.26794295,
        2.32176089],
       [2.81311736, 1.77022032, 1.77500479, ..., 1.50569265, 0.0289008 ,
        0.53799279],
       [6.74745483, 1.6983301 , 2.39539493, ..., 1.78672232, 0.3148532 ,
        1.40115553]])

In [13]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0         1          2          3          4          5     \
0    5.266267  4.455317   6.020252   7.064160   3.879081   7.832595   
1    6.237529  7.111324   3.897495   7.567360   6.504208   8.748242   
2    5.220927  3.519243   0.814437   2.809564   2.239427   0.993864   
3    2.813117  1.770220   1.775005   4.076981   1.773252   2.473703   
4    6.747455  1.698330   2.395395   2.069193   4.906382   6.896700   
..        ...       ...        ...        ...        ...        ...   
95   2.353129  0.200609   0.856152   2.007891   0.522542   1.508854   
96   2.735505  6.751500   4.879288   1.408865   0.029814   3.339953   
97  10.398968  6.822171  12.426260  11.050492   5.641633   4.631151   
98   8.388868  7.636179  12.901663  13.435951  13.015949  15.375913   
99   7.036324  5.641994   1.292135   3.879195   2.390861   3.890592   

         6          7          8          9     ...      2690       2691  \
0    6.206908   4.012881   2.451250   9.916734  ...  5.182984   3.939247   
1    5.852178   7.838470  10.669552  11.384312  ...  8.957099   5.933749   
2    2.645703   1.968755   4.340597   3.065435  ...  3.783379   1.116339   
3    2.276542   0.913681   0.413014   2.215124  ...  2.535008   0.802451   
4    5.157351   4.200436   5.904700   5.511260  ...  3.836722   2.385559   
..        ...        ...        ...        ...  ...       ...        ...   
95   0.109712   1.365325   0.422147   0.715428  ...  2.648821   0.339141   
96   5.937982   0.614069   1.848172   3.254341  ...  3.277685   1.771080   
97   3.706487   5.045554   4.678830   2.544201  ...  3.827351   4.489931   
98  11.171120  11.675467  16.426595  18.300577  ...  9.483502  13.808523   
99   7.279875   4.350122   6.072482   6.152210  ...  0.728999   8.097740   

         2692      2693       2694       2695       2696       2697      2698  \
0    2.557164  1.819603   3.166031   8.520838   4.682551   0.919427  0.700519   
1    6.439794  6.797908   9.074286   2.518282   6.395280   2.744432  0.732420   
2    2.455205  1.123117   0.324060   5.697121   1.784571   0.549514  0.267943   
3    1.909476  0.717837   0.629031   2.727555   0.583249   1.505693  0.028901   
4    0.838679  2.187659   2.165038   1.032202   2.572252   1.786722  0.314853   
..        ...       ...        ...        ...        ...        ...       ...   
95   4.066869  2.928934   2.638444   1.518893   5.797030   2.969650  4.926528   
96   1.674390  1.410516   2.256342   7.813653   3.658518   0.522463  0.163043   
97   1.151941  4.004724   6.116961   9.797121   4.449690   2.787932  0.477893   
98   3.012485  6.619841  11.136591  10.680456  11.797073  11.830114  9.633674   
99  10.110879  3.803605   1.107143   5.147954   5.102244   4.241060  0.536709   

         2699  
0    4.584303  
1    7.374718  
2    2.321761  
3    0.537993  
4    1.401156  
..        ...  
95   4.149217  
96   3.727905  
97   5.715654  
98  13.530163  
99   4.387613  

[100 rows x 2700 columns]

In [14]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRa_perturb.csv') 

# Add technical noise

In [25]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]


array([[ 3, 13,  5, ...,  2,  0,  2],
       [ 8,  3,  2, ...,  0,  0,  3],
       [ 1,  5,  3, ...,  0,  0,  1],
       [10,  1,  1, ...,  0,  0,  2]])

In [26]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O.csv') 

In [28]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 0, ..., 0, 1, 0],
       [2, 2, 0, ..., 1, 0, 0],
       [0, 2, 0, ..., 2, 0, 0],
       [6, 0, 0, ..., 2, 0, 1]])

In [29]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L.csv') 

In [30]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [31]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L_D.csv') 

# Run SERGIO with CRISPRi gene perturbations

In [32]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRi.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[ 7.72525409,  2.95843753, 11.60972175, ...,  4.5899805 ,
         2.01403288,  1.18321203],
       [ 3.45916029,  0.92443329,  1.42740769, ...,  0.92721584,
         0.92730415,  5.46993506],
       [ 0.08323557,  4.82283682,  3.96661644, ...,  0.36201732,
         2.24907249,  0.22419786],
       [ 7.02495789,  1.5365929 ,  0.89239988, ...,  0.1963121 ,
         1.18370644,  1.46587655]])

In [33]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0         1          2          3          4          5     \
0    6.263376  4.036806   6.547681   6.240117  13.946657   4.328626   
1    7.725254  2.958438  11.609722   9.150930   9.541440   5.381068   
2    3.459160  0.924433   1.427408   5.913417   0.249530   3.753577   
3    0.083236  4.822837   3.966616   0.368072   1.390202   2.568694   
4    7.024958  1.536593   0.892400   0.522832   3.546274   3.606492   
..        ...       ...        ...        ...        ...        ...   
95   2.696050  1.942870   0.201537   1.617369   0.836901   1.004719   
96   2.396467  2.998353   3.564014   5.952643   3.565933   3.613404   
97   5.043487  4.599972   7.726891   3.008907   4.452663   4.015303   
98  17.984010  9.287442   8.937976  14.443882  13.713259  13.663183   
99   4.801750  1.204089   6.875782   6.943284   6.967604   5.214487   

         6         7          8          9     ...       2690       2691  \
0    5.703986  4.966865   4.977107   6.688251  ...   1.855933   3.354489   
1    7.307132  2.909911   5.456767   8.524224  ...   7.381059   7.961509   
2    0.356265  3.047600   0.882627   1.931019  ...   0.000000   2.589619   
3    2.221143  2.087504   5.710673   1.557501  ...   0.268035   2.812606   
4    2.441651  2.663397   1.328837   0.577941  ...   1.118333   2.254918   
..        ...       ...        ...        ...  ...        ...        ...   
95   0.703915  0.525028   1.877005   5.532195  ...   3.467088   3.111192   
96   2.676141  1.952411   2.924348   1.956841  ...   5.156742   1.547597   
97   4.725798  3.961461   6.239811   5.875211  ...   5.760624   6.623473   
98  12.244201  9.442358  10.226879  13.595753  ...  13.367435  18.070606   
99   7.894290  7.314397   1.705206   6.088512  ...   4.437160   7.615450   

        2692       2693      2694       2695       2696      2697      2698  \
0   1.216914   4.276381  2.786392   3.186129   5.219347  3.956841  4.203140   
1   4.131200   4.681077  2.617458   6.404109  11.518527  4.589980  2.014033   
2   1.140223   2.936474  1.516707   5.235417   3.643153  0.927216  0.927304   
3   1.649703   2.086139  2.018234   0.312805   2.280586  0.362017  2.249072   
4   1.074100   1.239761  0.035521   0.566854   5.997339  0.196312  1.183706   
..       ...        ...       ...        ...        ...       ...       ...   
95  5.890047   3.068264  0.040681   3.249357   6.002888  1.649415  9.871249   
96  1.434975   0.957908  2.562400   2.371849   3.174202  3.139563  2.310021   
97  4.693607  12.589169  6.585128   0.947010  10.526223  4.504532  4.998541   
98  8.051400  14.490016  7.402030  12.718447  13.376472  7.501637  7.525170   
99  1.823384   7.312475  5.680335   6.503213   4.130301  1.289966  1.497083   

         2699  
0    4.947541  
1    1.183212  
2    5.469935  
3    0.224198  
4    1.465877  
..        ...  
95   4.083038  
96   0.000000  
97   4.609403  
98  10.103761  
99   7.650564  

[100 rows x 2700 columns]

In [34]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRi_perturb.csv') 

# Add technical noise

In [35]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]


array([[ 6,  2, 13, ...,  5,  1,  3],
       [ 2,  4,  0, ...,  0,  0,  6],
       [ 0,  5,  3, ...,  0,  1,  0],
       [12,  2,  0, ...,  0,  0,  1]])

In [36]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O.csv') 

In [38]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 4, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 2],
       [0, 1, 1, ..., 0, 2, 0],
       [2, 1, 2, ..., 0, 0, 1]])

In [39]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L.csv') 

In [40]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 4, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L_D.csv') 