In [1]:
import numpy as np
import pandas as pd
from sergio import sergio

import sys
locate_python = sys.exec_prefix
print(locate_python)

C:\Users\moha456\Anaconda3\envs\my_env


In [2]:
print("My numpy version is: ", np.__version__)

My numpy version is:  1.23.1


# Run SERGIO with CRISPRa gene perturbations

In [3]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRa.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[ 7.22700633,  2.85374701, 11.55712125, ..., 13.26430119,
         4.79344229,  3.30000556],
       [ 3.827265  ,  1.3662759 ,  5.55202763, ...,  5.43077426,
         2.83028358,  2.00014307],
       [ 0.43364916,  3.89750727,  3.24550339, ...,  0.81246863,
         2.17718154,  0.55083107],
       [ 2.06256545,  0.67796971,  4.15225979, ...,  9.15561143,
         2.95175474,  1.4819771 ]])

In [4]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0          1          2          3          4          5     \
0    5.535301   6.003322   8.180281   8.450988   5.138767   6.274323   
1    7.227006   2.853747  11.557121  15.496791   7.808239   8.665840   
2    3.827265   1.366276   5.552028   5.818034   1.681415   2.664449   
3    0.433649   3.897507   3.245503   1.017048   1.199901   1.707773   
4    2.062565   0.677970   4.152260   3.482083   2.329159   2.025384   
..        ...        ...        ...        ...        ...        ...   
95   4.675658   0.645706   0.961234   5.236385   1.828150   0.626070   
96   2.850519   3.463872   2.488585   3.895334   1.036005   2.350069   
97   5.250381   3.564580   8.049723   4.724126  13.573672   9.030849   
98  10.010398  10.313982  16.715167   5.818939   9.780866  10.371681   
99   2.066502   9.097627   3.237068   3.423362  10.508681  12.460944   

         6          7          8         9     ...       2690       2691  \
0    6.068952   8.319344   9.596792  3.346097  ...   6.874920   3.466555   
1   13.592270  11.532887   9.362546  9.261457  ...  13.602394   3.824414   
2    3.774367   5.576177   5.950058  1.134771  ...   5.542584   6.990537   
3    1.443112   3.010442   2.473156  3.028400  ...   1.210341   2.981321   
4    3.040260   4.168471   1.792022  4.168772  ...   2.285937   6.236115   
..        ...        ...        ...       ...  ...        ...        ...   
95   4.504433   0.879707   0.602816  0.885027  ...   3.473858   3.081591   
96   4.568506   2.578959   6.712498  1.560023  ...   4.375320   3.795355   
97   4.335520   8.589940   5.382722  9.870239  ...   8.447717   2.743280   
98   4.570592  16.493043  15.540610  8.827459  ...   7.641634  14.799599   
99   4.622959   3.051332   9.025336  7.591917  ...   4.687605   4.336905   

        2692      2693      2694      2695       2696       2697      2698  \
0   4.904786  3.597713  1.618729  3.939370   6.178675   5.474416  6.300427   
1   3.474101  1.766341  5.484814  4.011228  12.648388  13.264301  4.793442   
2   3.399465  2.220369  2.489799  2.144092   4.604199   5.430774  2.830284   
3   0.846970  2.587848  0.947640  0.364526   1.597531   0.812469  2.177182   
4   3.562837  1.584779  4.190885  2.958502   6.228540   9.155611  2.951755   
..       ...       ...       ...       ...        ...        ...       ...   
95  3.012707  2.140917  3.393632  1.900385   4.271889   2.447367  6.899111   
96  0.978231  2.905730  2.908801  1.512791   0.999930   1.118527  0.781708   
97  2.828169  0.450656  4.777371  5.845821   4.718291   3.410822  1.506034   
98  5.384277  9.485337  7.130673  8.650680  10.728688   9.395892  7.337448   
99  2.054362  5.021146  3.852963  3.473003   5.358465   4.781222  1.001767   

        2699  
0   5.447564  
1   3.300006  
2   2.000143  
3   0.550831  
4   1.481977  
..       ...  
95  5.029252  
96  1.889732  
97  4.941601  
98  7.258279  
99  5.865005  

[100 rows x 2700 columns]

In [8]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRa_perturb.csv') 

# Add technical noise

In [9]:
# dropout
binary_ind = sim.dropout_indicator(expr, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[2, 0, 0, ..., 3, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_only_D.csv') 

# Run SERGIO with CRISPRi gene perturbations

In [16]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRi.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[9.92918319, 2.03614892, 4.15930886, ..., 4.21627538, 4.88591634,
        7.0442186 ],
       [5.3259844 , 1.15116769, 2.54975922, ..., 1.1918243 , 4.71424809,
        3.01937419],
       [3.31585009, 0.44145351, 4.85456201, ..., 1.11289832, 2.04052377,
        4.09034157],
       [3.13522786, 1.42725825, 2.45794321, ..., 2.44302698, 1.04846463,
        5.41995751]])

In [17]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0          1          2          3          4          5     \
0    5.869034   2.038605   7.816396   2.579736   1.184978   4.292760   
1    9.929183   2.036149   4.159309   1.791175   3.615640   6.977682   
2    5.325984   1.151168   2.549759   1.185818   2.523513   1.146318   
3    3.315850   0.441454   4.854562   0.085201   2.074086   4.418740   
4    3.135228   1.427258   2.457943   1.690138   3.308151   3.381021   
..        ...        ...        ...        ...        ...        ...   
95   5.070494   1.856574   2.641160   1.404944   1.645732   1.064712   
96   3.605715   1.562356   0.200647   0.789489   5.483439   5.514960   
97   0.281056  11.350075   4.098413  11.233223   6.949322   4.155181   
98  12.141911  14.597187  16.975876  17.237337  10.540688  12.848358   
99   1.989790  10.315233   8.869146  10.057603   7.670567   8.766036   

         6          7          8          9     ...      2690      2691  \
0    7.170892   3.947073  10.093016   6.137267  ...  3.835654  3.932662   
1   15.023292   3.238314  11.616273   8.974506  ...  4.566184  1.854076   
2    4.672625   4.685862   2.265155   4.857825  ...  4.411493  2.384247   
3    1.878477   1.710237   2.684333   2.463417  ...  0.748276  0.642141   
4    4.267225   1.601534   2.108091   2.951835  ...  2.219248  0.583818   
..        ...        ...        ...        ...  ...       ...       ...   
95   2.428919   0.004973   2.568704   3.148297  ...  3.414676  2.189299   
96   2.146407   3.615656   2.309918   2.707519  ...  1.906406  2.697776   
97   2.776575   5.215263   2.861328   6.969993  ...  3.595143  6.211649   
98   5.089791  14.146877   9.922909  13.539920  ...  9.064696  7.473405   
99   8.375194  10.112279   4.182182   5.114728  ...  5.459318  7.704075   

         2692      2693      2694      2695       2696      2697       2698  \
0    6.155266  0.212438  3.803839  2.016000   4.824091  0.402331   7.914665   
1    8.581313  1.327127  8.296713  2.507866   3.222791  4.216275   4.885916   
2    7.166543  2.143105  1.054042  1.428461   1.386864  1.191824   4.714248   
3    5.230519  0.443789  0.161917  0.594770   0.699516  1.112898   2.040524   
4    2.024792  0.742986  1.352501  0.905491   0.000000  2.443027   1.048465   
..        ...       ...       ...       ...        ...       ...        ...   
95   6.132126  2.801179  0.565261  8.847635   7.525674  7.103136   3.419578   
96   0.244838  1.997416  0.430418  0.847233   5.760105  0.086282   0.820761   
97   3.713875  4.149349  6.122704  2.003278   2.494943  3.457371   4.503302   
98  13.951825  5.461263  7.804275  7.898832  11.836918  8.946491  11.034548   
99   2.574320  6.623754  5.398969  4.976247   6.066471  4.039718   2.975487   

        2699  
0   1.748104  
1   7.044219  
2   3.019374  
3   4.090342  
4   5.419958  
..       ...  
95  5.559600  
96  4.184238  
97  6.801890  
98  8.528692  
99  8.154749  

[100 rows x 2700 columns]

In [18]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRi_perturb.csv') 

# Add technical noise

In [19]:
# dropout
binary_ind = sim.dropout_indicator(expr, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[2, 0, 0, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_Only_D.csv') 