In [27]:
import numpy as np
import pandas as pd
from sergio import sergio

import sys
locate_python = sys.exec_prefix
print(locate_python)

C:\Users\moha456\Anaconda3\envs\my_env


In [28]:
print("My numpy version is: ", np.__version__)

My numpy version is:  1.23.1


# Run SERGIO for FadR

In [29]:
sim = sergio(number_genes=25, number_bins = 1, number_sc = 100, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='FadR_targets.txt', input_file_regs='FadR_regs.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

Start simulating new level
There are 1 genes to simulate in this layer
Done with current level
Start simulating new level
There are 3 genes to simulate in this layer
Done with current level
Start simulating new level
There are 21 genes to simulate in this layer
Done with current level


0         1         2         3         4         5         6   \
0   4.601432  2.065899  4.388833  0.913124  0.030592  2.964596  1.993469   
1   4.010586  3.245141  3.584761  5.057743  6.218854  4.617223  4.272583   
2   3.069674  1.153391  3.948587  3.048129  5.190139  2.319551  1.462685   
3   1.383219  1.997294  1.905523  1.744135  4.941050  2.359568  2.712477   
4   1.249583  1.638096  1.930984  2.241829  1.087513  3.477142  4.562916   
5   0.342298  0.579870  1.056125  0.827504  0.592827  0.062833  1.139474   
6   0.408117  0.000000  0.755406  2.151505  2.579257  0.941447  0.422803   
7   1.598434  2.040867  0.103463  3.377898  1.951495  2.220130  3.531169   
8   2.291318  3.006623  2.856287  3.052299  5.439846  1.366752  1.795646   
9   3.006393  0.928944  2.586975  2.073641  1.784427  1.700256  0.799790   
10  2.281082  1.296668  0.070589  1.320575  0.500348  0.000000  0.544161   
11  4.469094  0.000000  3.183420  3.973128  1.412513  3.106712  0.368385   
12  2.666974  3.856348  6.304674  4.846298  6.350467  2.229062  1.754039   
13  3.127919  1.507039  5.433587  1.772771  2.898684  4.533504  1.415480   
14  1.221413  3.758505  1.322797  2.146839  1.320428  3.370127  4.810069   
15  2.547944  0.697858  5.100335  1.547225  1.635125  3.240737  5.329327   
16  0.045639  0.897206  2.524654  2.450271  0.760586  2.247357  2.387762   
17  1.281215  2.856454  1.592524  5.127450  0.128987  4.226160  1.339458   
18  1.403236  0.001899  1.662046  0.910858  0.660437  0.208452  0.205011   
19  0.945164  1.296218  2.775413  0.075049  1.157144  1.300009  1.305858   
20  2.974705  1.001741  1.633629  0.959790  0.081610  0.827794  1.004662   
21  1.857977  3.647804  1.477800  1.147693  5.368157  2.095334  4.654515   
22  0.070628  0.421031  1.520396  1.796046  0.234281  1.118279  0.962443   
23  2.023573  2.306131  1.121931  0.000000  0.170700  0.819649  1.101275   
24  1.071153  3.099367  2.460667  2.708664  2.663663  2.848644  4.412949   

           7         8         9   ...        90        91        92  \
0    5.856235  5.120469  0.496652  ...  2.327568  0.598081  1.030657   
1    1.717539  3.398419  9.526030  ...  4.422261  6.988722  7.211552   
2    1.955781  3.844643  3.510606  ...  3.223387  3.978841  3.580613   
3    1.434968  2.397057  4.648568  ...  0.862110  3.294267  3.364170   
4    2.917273  1.987200  1.085570  ...  2.353102  1.283363  0.923654   
5    1.033880  0.735024  1.245486  ...  0.546986  0.098228  1.353225   
6    2.034574  0.597240  2.053792  ...  1.019442  1.819288  1.853967   
7    1.636337  0.087696  2.333970  ...  2.681568  2.029848  1.721020   
8    1.857883  2.567180  1.509871  ...  1.609889  0.421508  0.636769   
9    4.633987  2.411129  0.589262  ...  1.866586  1.383451  2.778072   
10   0.402167  0.025782  0.572505  ...  0.145644  1.216665  1.636036   
11   3.742571  3.124599  1.005779  ...  3.591244  1.704077  2.397341   
12  10.607516  6.242186  0.994774  ...  4.591569  0.234307  0.856491   
13   3.093512  5.377189  6.926351  ...  2.070988  5.949096  4.430210   
14   1.438479  1.591126  0.729561  ...  1.523720  0.430781  0.634685   
15   1.992265  5.444587  0.539099  ...  3.861826  0.609055  1.053049   
16   0.475833  2.289799  3.378873  ...  2.893020  3.326211  1.538024   
17   1.897657  1.722749  3.004029  ...  4.821537  1.875563  4.052798   
18   1.256184  1.955436  0.635550  ...  0.400680  0.274850  0.000000   
19   4.383914  2.365133  1.348559  ...  0.522177  2.771212  3.636369   
20   1.168190  1.741805  2.019304  ...  1.712169  1.725502  2.396113   
21   3.490088  1.561085  7.099941  ...  1.757467  6.968408  4.977133   
22   0.083815  1.149100  0.221417  ...  2.328030  0.143677  0.104136   
23   0.463515  0.840527  1.219902  ...  0.213778  2.000079  1.396803   
24   0.897910  2.073188  3.494338  ...  2.833801  2.229776  0.919562   

           93        94        95        96        97        98        99  
0    5.552105  5.582792  1.683472  0.336994  5.812165  0.238007  2.099325  
1    5.6

In [30]:
# save to csv
df_output.to_csv('GeneExpression_Ecoli_FadR.csv') 

# Run SERGIO for Lacl

In [32]:
sim = sergio(number_genes=3, number_bins = 1, number_sc = 100, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='LacI_targets.txt', input_file_regs='LacI_regs.txt', shared_coop_state=0)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

KeyError: 3

In [20]:
# save to csv
df_output.to_csv('GeneExpression_Ecoli_Lacl.csv')

# Run SERGIO for TyrR

In [33]:
sim = sergio(number_genes=11, number_bins = 1, number_sc = 100, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='TyrR_targets.txt', input_file_regs='TyrR_regs.txt', shared_coop_state=0)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
df_output = pd.DataFrame(expr_clean_ss)
df_output

KeyError: 11

In [22]:
# save to csv
df_output.to_csv('GeneExpression_Ecoli_TyrR.csv') 

# Add technical noise

In [14]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
#expr_O[1:5]

In [15]:
expr_O = np.concatenate(expr_O, axis = 1)
expr_O[1:5]

array([[ 9.75382198, 11.75973383,  8.94737041, ...,  3.89390402,
        10.65061723,  7.4047379 ],
       [ 2.56473823,  2.04671179,  2.34279775, ...,  2.36978405,
         4.17948816,  3.76350467],
       [ 0.56392336,  3.57097325,  0.75411455, ...,  0.28559197,
         4.49877286,  3.01216592],
       [ 7.92188203,  5.44624439,  7.82676335, ...,  7.46016408,
         7.51338103,  3.6327506 ]])

In [16]:
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O.csv') 

In [28]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 0, ..., 0, 1, 0],
       [2, 2, 0, ..., 1, 0, 0],
       [0, 2, 0, ..., 2, 0, 0],
       [6, 0, 0, ..., 2, 0, 1]])

In [29]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L.csv') 

In [30]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [31]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRa_perturb_tech_O_L_D.csv') 

# Run SERGIO with CRISPRi gene perturbations

In [32]:
sim = sergio(number_genes=100, number_bins = 9, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='steady-state_input_GRN_CRISPRai.txt', input_file_regs='steady-state_input_MRs_CRISPRi.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean_ss = np.concatenate(expr, axis = 1)
expr_clean_ss[1:5]

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 6 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


array([[ 7.72525409,  2.95843753, 11.60972175, ...,  4.5899805 ,
         2.01403288,  1.18321203],
       [ 3.45916029,  0.92443329,  1.42740769, ...,  0.92721584,
         0.92730415,  5.46993506],
       [ 0.08323557,  4.82283682,  3.96661644, ...,  0.36201732,
         2.24907249,  0.22419786],
       [ 7.02495789,  1.5365929 ,  0.89239988, ...,  0.1963121 ,
         1.18370644,  1.46587655]])

In [33]:
expr_clean_ss 
df_output = pd.DataFrame(expr_clean_ss) 
df_output 

0         1          2          3          4          5     \
0    6.263376  4.036806   6.547681   6.240117  13.946657   4.328626   
1    7.725254  2.958438  11.609722   9.150930   9.541440   5.381068   
2    3.459160  0.924433   1.427408   5.913417   0.249530   3.753577   
3    0.083236  4.822837   3.966616   0.368072   1.390202   2.568694   
4    7.024958  1.536593   0.892400   0.522832   3.546274   3.606492   
..        ...       ...        ...        ...        ...        ...   
95   2.696050  1.942870   0.201537   1.617369   0.836901   1.004719   
96   2.396467  2.998353   3.564014   5.952643   3.565933   3.613404   
97   5.043487  4.599972   7.726891   3.008907   4.452663   4.015303   
98  17.984010  9.287442   8.937976  14.443882  13.713259  13.663183   
99   4.801750  1.204089   6.875782   6.943284   6.967604   5.214487   

         6         7          8          9     ...       2690       2691  \
0    5.703986  4.966865   4.977107   6.688251  ...   1.855933   3.354489   
1    7.307132  2.909911   5.456767   8.524224  ...   7.381059   7.961509   
2    0.356265  3.047600   0.882627   1.931019  ...   0.000000   2.589619   
3    2.221143  2.087504   5.710673   1.557501  ...   0.268035   2.812606   
4    2.441651  2.663397   1.328837   0.577941  ...   1.118333   2.254918   
..        ...       ...        ...        ...  ...        ...        ...   
95   0.703915  0.525028   1.877005   5.532195  ...   3.467088   3.111192   
96   2.676141  1.952411   2.924348   1.956841  ...   5.156742   1.547597   
97   4.725798  3.961461   6.239811   5.875211  ...   5.760624   6.623473   
98  12.244201  9.442358  10.226879  13.595753  ...  13.367435  18.070606   
99   7.894290  7.314397   1.705206   6.088512  ...   4.437160   7.615450   

        2692       2693      2694       2695       2696      2697      2698  \
0   1.216914   4.276381  2.786392   3.186129   5.219347  3.956841  4.203140   
1   4.131200   4.681077  2.617458   6.404109  11.518527  4.589980  2.014033   
2   1.140223   2.936474  1.516707   5.235417   3.643153  0.927216  0.927304   
3   1.649703   2.086139  2.018234   0.312805   2.280586  0.362017  2.249072   
4   1.074100   1.239761  0.035521   0.566854   5.997339  0.196312  1.183706   
..       ...        ...       ...        ...        ...       ...       ...   
95  5.890047   3.068264  0.040681   3.249357   6.002888  1.649415  9.871249   
96  1.434975   0.957908  2.562400   2.371849   3.174202  3.139563  2.310021   
97  4.693607  12.589169  6.585128   0.947010  10.526223  4.504532  4.998541   
98  8.051400  14.490016  7.402030  12.718447  13.376472  7.501637  7.525170   
99  1.823384   7.312475  5.680335   6.503213   4.130301  1.289966  1.497083   

         2699  
0    4.947541  
1    1.183212  
2    5.469935  
3    0.224198  
4    1.465877  
..        ...  
95   4.083038  
96   0.000000  
97   4.609403  
98  10.103761  
99   7.650564  

[100 rows x 2700 columns]

In [34]:
# save to csv
df_output.to_csv('GeneExpression_CRISPRi_perturb.csv') 

# Add technical noise

In [35]:
# outlier genes
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
count_matrix = sim.convert_to_UMIcounts(expr_O)
expr_tech_ss_O = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O[1:5]


array([[ 6,  2, 13, ...,  5,  1,  3],
       [ 2,  4,  0, ...,  0,  0,  6],
       [ 0,  5,  3, ...,  0,  1,  0],
       [12,  2,  0, ...,  0,  0,  1]])

In [36]:
df_output = pd.DataFrame(expr_tech_ss_O) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O.csv') 

In [38]:
# library size
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
count_matrix = sim.convert_to_UMIcounts(expr_O_L)
expr_tech_ss_O_L = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L[1:5]

array([[1, 1, 4, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 2],
       [0, 1, 1, ..., 0, 2, 0],
       [2, 1, 2, ..., 0, 0, 1]])

In [39]:
df_output = pd.DataFrame(expr_tech_ss_O_L) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L.csv') 

In [40]:
# dropout
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 82)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
expr_tech_ss_O_L_D = np.concatenate(count_matrix, axis = 1)
expr_tech_ss_O_L_D[1:5]


array([[0, 0, 4, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
df_output = pd.DataFrame(expr_tech_ss_O_L_D) 
df_output 
df_output.to_csv('GeneExpression_CRISPRi_perturb_tech_O_L_D.csv') 